rm(list=ls())
install.packages(c('rJava', 'XML', 'sp', 'raster', 'dismo', 'rgdal'))
setwd("F:/Diploma/sarcoscypha-ukraine/Data")
getwd()
df <- read.csv('sarco.csv')
library(maptools)
xlim=c(22,40)
ylim=c(44,52.5)
data(wrld_simpl)
plot(wrld_simpl,xlim=xlim,ylim=ylim,col='olivedrab3',bg='lightblue')
points(df$Longitude, df$Latitude, col='red')
library(dismo)
library(terra)
install.packages('dismo')
?terra
